version: '3'
services:
  backend:
    build: ./backend
    working_dir: '/root/volumes'
    tty: true
    volumes:
      - ./backend/volumes:/root/volumes
      - ./docs/backend:/root/docs/backend
    network_mode: "host"
    env_file:
      - ./backend/.env
  rdb:
    build: ./rdb/postgresql
    # restart: always
    ports: 
      - "5432:5432"
    volumes:
      # ストレージのマウント
      - ./rdb/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres