services:
  schemaspy:
    build: ./documentation/schemaspy
    volumes:
      - ./docs/rdb/schemaspy:/output # export先
      # - ./documentation/schemaspy/config:/config
      - ./documentation/schemaspy/config:/config
      # - ./backend/volumes:/backend/volumes # 参照先（sqlite）
    extra_hosts: # linux環境の場合にhost.docker.internalでhost上にアクセスするために必要
      - "host.docker.internal:host-gateway"
    networks:
      - webapp-fastapi-master_webapp_fastapi_master_network

networks:
  webapp-fastapi-master_webapp_fastapi_master_network:
    external: true