services:
  backend:
    build: ./backend
    working_dir: '/root/volumes'
    tty: true
    volumes:
      - ./backend/volumes:/root/volumes
      - ./docs/backend:/root/docs/backend
    # network_mode: "host"
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    extra_hosts: # linux環境の場合にhost.docker.internalでhost上にアクセスするために必要
      - "host.docker.internal:host-gateway"
    networks:
      - master_webapp_network
  postgres:
    build: ./rdb/postgresql
    # restart: always
    ports: 
      - "5432:5432"
    volumes:
      # ストレージのマウント
      - ./rdb/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - master_webapp_network
  # tika: 
  #   image: imixs/tika
  #   ports:
  #     - "9998:9998"
  #   networks:
  #     - master_webapp_network

  mkdocs:
    build:
      context: ./documentation/mkdocs
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "48080:48080"
    working_dir: /root/projects/volume
    command: mkdocs serve
    volumes:
      - type: bind
        source: "./documentation/mkdocs/volume"
        target: "/root/projects/volume"
      - type: bind # build先
        source: "./docs/mkdocs"
        target: "/root/projects/volume/site"

networks:
  master_webapp_network:
    driver: bridge